"""Turn a profile into a starter pipeline and rule set.

``suggest(df)`` profiles the raw frame and writes down what a careful analyst
would do next:

* a ``steps.yaml`` that renames headers, trims whitespace, parses the types
  the profiler inferred, merges spelling variants of categories onto one
  canonical spelling, standardizes emails / phones / names / addresses,
  flags outliers, and deduplicates on the detected identifier;
* a ``rules.yaml`` that asserts what the cleaned data should look like:
  ``not_null`` for complete columns, ``unique`` + ``dtype`` for identifiers,
  ``allowed`` for low-cardinality categories, email and E.164 regexes, numeric
  ranges from the observed quartiles, and date-order checks that held on
  every row.

Rules are written against the snake_cased output of the suggested pipeline.
Both files are commented so every choice can be reviewed; judgement calls
(imputing missing values, capping instead of flagging outliers) are left as
commented-out alternatives rather than applied silently.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd
import yaml

from .clean import _missing_frame, _missing_series, parse_number_column, snake_case_columns
from .dates import parse_dates
from .profile import ColumnProfile, ProfileReport, profile_dataframe

EMAIL_REGEX = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
E164_REGEX = r"^\+[1-9]\d{6,14}(;ext=\d+)?$"


@dataclass
class SuggestedStep:
    step: dict[str, Any]
    comment: list[str] = field(default_factory=list)
    active: bool = True
    core: bool = True  # part of the safe default pass used by `cleankit clean`


@dataclass
class Suggestion:
    name: str
    source: str
    profile: ProfileReport
    steps: list[SuggestedStep]
    rules: dict[str, Any]
    rule_comments: dict[str, list[str]] = field(default_factory=dict)

    @property
    def pipeline(self) -> dict[str, Any]:
        """The active steps as a pipeline config (what ``load_pipeline`` returns)."""
        return {"name": self.name, "steps": [s.step for s in self.steps if s.active]}

    def core_pipeline(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "steps": [s.step for s in self.steps if s.active and s.core],
        }

    def steps_yaml(self) -> str:
        out = [
            f"# Starter cleaning pipeline for {self.source}, generated by `cleankit suggest`.",
            f"# Profiled {self.profile.n_rows} rows x {self.profile.n_cols} columns, "
            f"{self.profile.n_issues} suspected issues.",
            "# Review every step; commented-out blocks are judgement calls left to you.",
            "# Run it with:",
            f"#   cleankit run-pipeline {self.source} --steps steps.yaml --out cleaned.csv",
            "",
            f"name: {_scalar(self.name)}",
            "",
            "steps:",
        ]
        for s in self.steps:
            out.append("")
            for line in s.comment:
                out.append(f"  # {line}" if line else "  #")
            body = _emit_mapping_item(s.step, indent=2)
            if not s.active:
                body = [
                    "  # " + line[2:] if line.startswith("  ") else "# " + line
                    for line in body
                ]
            out.extend(body)
        return "\n".join(out) + "\n"

    def rules_yaml(self) -> str:
        out = [
            f"# Validation rules for the cleaned output of {self.source}, generated by",
            "# `cleankit suggest`. Column names are the snake_cased names the pipeline",
            "# writes. Ranges come from the observed quartiles (3x IQR, rounded out),",
            "# so values the profiler flagged as outliers are expected to fail.",
            "# Run with:",
            "#   cleankit validate cleaned.csv --rules rules.yaml",
            "",
            "columns:" if self.rules["columns"] else "columns: {}",
        ]
        for col, spec in self.rules["columns"].items():
            for line in self.rule_comments.get(col, []):
                out.append(f"  # {line}")
            out.append(f"  {_key(col)}:")
            for rule, value in spec.items():
                if isinstance(value, dict):
                    out.append(f"    {rule}:")
                    for k, v in value.items():
                        out.append(f"      {k}: {_scalar(v)}")
                else:
                    out.append(f"    {rule}: {_value(value)}")
        out.append("")
        if self.rules["checks"]:
            out.append("# Cross-field checks that held on every row of the sample.")
            out.append("checks:")
            for check in self.rules["checks"]:
                out.extend(_emit_mapping_item(check, indent=2))
        else:
            out.append("checks: []")
        return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# YAML emission (small, predictable, round-trips through yaml.safe_load)
# ---------------------------------------------------------------------------


def _scalar(value: Any) -> str:
    text = yaml.safe_dump([value], default_flow_style=True, allow_unicode=True, width=10_000)
    return text.strip()[1:-1]


def _key(value: Any) -> str:
    return _scalar(str(value))


def _value(value: Any) -> str:
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_scalar(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{_key(k)}: {_value(v)}" for k, v in value.items()) + "}"
    return _scalar(value)


def _emit_mapping_item(item: dict[str, Any], indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    first = True
    for k, v in item.items():
        prefix = f"{pad}- " if first else f"{pad}  "
        first = False
        if isinstance(v, dict) and v:
            lines.append(f"{prefix}{_key(k)}:")
            for kk, vv in v.items():
                lines.append(f"{pad}    {_key(kk)}: {_value(vv)}")
        else:
            lines.append(f"{prefix}{_key(k)}: {_value(v)}")
    return lines


# ---------------------------------------------------------------------------
# Suggestion logic
# ---------------------------------------------------------------------------


def _nice(x: float, up: bool) -> float:
    """Round outward to two significant digits (125 -> 130, -8450 -> -8500)."""
    if x == 0 or not math.isfinite(x):
        return 0.0 if not math.isfinite(x) else x
    mag = 10 ** (math.floor(math.log10(abs(x))) - 1)
    return (math.ceil(x / mag) if up else math.floor(x / mag)) * mag


def _as_number(x: float) -> int | float:
    return int(x) if float(x).is_integer() else float(x)


def _numbers(series: pd.Series) -> np.ndarray:
    nums, _, _ = parse_number_column(series.tolist())
    return np.asarray([n for n in nums if n is not None], dtype="float64")


def _range_rule(values: np.ndarray, integer: bool) -> dict[str, Any] | None:
    if values.size < 4:
        return None
    q1, q3 = np.percentile(values, [25, 75])
    iqr = q3 - q1
    if iqr == 0:
        return None
    low, high = q1 - 3 * iqr, q3 + 3 * iqr
    lo = 0.0 if (values.min() >= 0 and low < 0) else _nice(low, up=False)
    hi = _nice(high, up=True)
    if integer:
        lo, hi = math.floor(lo), math.ceil(hi)
    return {"min": _as_number(lo), "max": _as_number(hi)}


def _empty_row_mask(df: pd.DataFrame, id_cols: list[str]) -> pd.Series:
    others = [c for c in df.columns if c not in id_cols]
    if not others:
        return pd.Series(False, index=df.index)
    return _missing_frame(df[others]).all(axis=1)


def suggest(
    df: pd.DataFrame,
    default_region: str = "PA",
    name: str = "suggested",
    source: str = "data.csv",
) -> Suggestion:
    """Profile ``df`` (raw strings, as read by the CLI) and suggest steps and rules."""
    from .contacts import _check_region

    region = _check_region(default_region)
    report = profile_dataframe(df)
    raw_cols = list(df.columns)
    snake = dict(zip(raw_cols, snake_case_columns(raw_cols)))
    prof: dict[str, ColumnProfile] = {c: report.column(str(c)) for c in raw_cols}

    ids = [c for c in raw_cols if prof[c].semantic == "identifier"]
    countries = [c for c in raw_cols if prof[c].semantic == "country"]
    empty_rows = _empty_row_mask(df, ids) if ids else pd.Series(False, index=df.index)
    kept = df[~empty_rows]

    steps: list[SuggestedStep] = []
    renamed = {str(c): snake[c] for c in raw_cols if str(c) != snake[c]}
    steps.append(
        SuggestedStep(
            {"op": "standardize_column_names"},
            [f"Headers to snake_case: {len(renamed)} renamed"
             + (f" (e.g. '{next(iter(renamed))}' -> {next(iter(renamed.values()))})." if renamed else ".")],
        )
    )
    blank_cols = [snake[c] for c in raw_cols if any("whitespace" in i.lower() for i in prof[c].issues)]
    steps.append(
        SuggestedStep(
            {"op": "normalize_whitespace"},
            ["Trim, collapse repeated spaces, NFKC-normalise; whitespace-only cells become null."]
            + ([f"Whitespace problems found in: {', '.join(blank_cols)}."] if blank_cols else []),
        )
    )

    if int(empty_rows.sum()):
        id_list = ", ".join(snake[c] for c in ids)
        others = [snake[c] for c in raw_cols if c not in ids]
        steps.append(
            SuggestedStep(
                {"op": "handle_missing", "strategy": "drop_rows", "columns": others, "how": "all"},
                [f"{int(empty_rows.sum())} row(s) hold nothing but an identifier ({id_list});",
                 "drop them. Each dropped row is listed in the audit log."],
                core=False,
            )
        )

    mapping: dict[str, str] = {}
    notes: list[str] = []
    for c in raw_cols:
        p = prof[c]
        if p.inferred_type in {"integer", "float", "boolean", "datetime"}:
            mapping[snake[c]] = p.inferred_type
            detail = [i for i in p.issues if i.startswith(("Mixed", "Ambiguous", "Numbers stored", "Inconsistent boolean", "Day-first"))]
            if detail:
                notes.append(f"{snake[c]}: {detail[0]}")
    if mapping:
        steps.append(
            SuggestedStep(
                {"op": "coerce_types", "mapping": mapping},
                ["Parse raw text into real types (dates per value, ISO-safe; numbers with",
                 "separators resolved from column context)."] + notes[:6],
            )
        )

    for c in raw_cols:
        p = prof[c]
        if p.inferred_type not in {"categorical", "text"} or not p.clusters:
            continue
        variants = [cl for cl in p.clusters if len(cl["variants"]) > 1]
        if not variants:
            continue
        from .text import canonical_key

        canonical = [cl["canonical"] for cl in p.clusters]
        aliases: dict[str, str] = {}
        for cl in p.clusters:
            ckey = canonical_key(cl["canonical"])
            for value, _ in cl["variants"]:
                if canonical_key(value) != ckey:
                    aliases[value] = cl["canonical"]
        step: dict[str, Any] = {
            "op": "standardize_categoricals",
            "column": snake[c],
            "canonical": canonical,
            "threshold": 0.9,
        }
        if aliases:
            step["extra_aliases"] = aliases
        spell = "; ".join(
            f"{cl['canonical']} <- " + ", ".join(v for v, _ in cl["variants"][1:4])
            for cl in variants[:3]
        )
        steps.append(
            SuggestedStep(
                step,
                [f"'{snake[c]}' has {sum(len(cl['variants']) for cl in variants)} spellings of "
                 f"{len(variants)} value(s): {spell}."],
            )
        )

    region_column = snake[countries[0]] if countries else None
    for c in raw_cols:
        p = prof[c]
        col = snake[c]
        if p.inferred_type == "email":
            steps.append(
                SuggestedStep(
                    {"op": "standardize_emails", "columns": [col], "invalid": "keep"},
                    ["Lower-case and repair provider typos (gmial.com, .con). Malformed",
                     "addresses are kept and reported; switch invalid to null or flag."],
                )
            )
        elif p.inferred_type == "phone":
            step = {"op": "standardize_phones", "columns": [col], "default_region": region}
            if region_column:
                step["region_column"] = region_column
            steps.append(
                SuggestedStep(
                    step,
                    ["Rewrite phones as E.164."
                     + (f" Each row's region comes from '{region_column}';" if region_column else "")
                     + f" numbers without a country code default to {region}."],
                )
            )
        elif p.semantic == "person_name":
            steps.append(
                SuggestedStep(
                    {"op": "standardize_names", "columns": [col]},
                    ["Title-case names, keeping particles (de, del, la) and O'/Mc forms."],
                )
            )
        elif p.semantic == "address":
            steps.append(
                SuggestedStep(
                    {"op": "clean_addresses", "columns": [col]},
                    ["Expand street abbreviations (Ave, Edif, Apto, Cra) and tidy spacing."],
                )
            )

    for c in raw_cols:
        p = prof[c]
        if p.inferred_type in {"integer", "float"} and p.semantic != "identifier" and p.n_missing:
            nums = _numbers(kept[c]) if len(kept) else np.array([])
            if nums.size:
                med = float(np.median(nums))
                steps.append(
                    SuggestedStep(
                        {"op": "handle_missing", "strategy": "fill", "columns": [snake[c]], "value": "median"},
                        [f"'{snake[c]}' is missing in {p.n_missing} row(s). Imputing is a judgement",
                         f"call: uncomment to fill with the median ({_as_number(round(med, 4))})."],
                        active=False,
                        core=False,
                    )
                )
    outlier_cols = [snake[c] for c in raw_cols if prof[c].n_outliers and prof[c].semantic != "identifier"]
    if outlier_cols:
        steps.append(
            SuggestedStep(
                {"op": "handle_outliers", "columns": outlier_cols, "method": "iqr", "action": "flag"},
                [f"Potential outliers in {', '.join(outlier_cols)} (1.5x IQR). Flag them for review",
                 "(adds <col>_is_outlier); change action to cap to winsorize instead."],
                core=False,
            )
        )

    if ids and any(prof[c].details.get("conflicting_keys") or prof[c].details.get("duplicate_row_keys") for c in ids):
        c = ids[0]
        conflicting = prof[c].details.get("conflicting_keys", [])
        exact = prof[c].details.get("duplicate_row_keys", [])
        steps.append(
            SuggestedStep(
                {"op": "deduplicate", "subset": [snake[c]], "keep": "most_complete"},
                [f"'{snake[c]}' repeats: {len(exact)} exact duplicate row(s), {len(conflicting)} key(s) with",
                 "differing rows. Keep the most complete row of each; every removal is",
                 "logged with the row it duplicated."],
            )
        )
    elif report.n_duplicate_rows:
        steps.append(
            SuggestedStep(
                {"op": "deduplicate", "keep": "first"},
                [f"{report.n_duplicate_rows} exact duplicate row(s)."],
            )
        )

    rules, comments = _suggest_rules(df, kept, raw_cols, snake, prof, steps)
    return Suggestion(
        name=name,
        source=source,
        profile=report,
        steps=steps,
        rules=rules,
        rule_comments=comments,
    )


def _suggest_rules(
    df: pd.DataFrame,
    kept: pd.DataFrame,
    raw_cols: list[Any],
    snake: dict[Any, str],
    prof: dict[Any, ColumnProfile],
    steps: list[SuggestedStep],
) -> tuple[dict[str, Any], dict[str, list[str]]]:
    columns: dict[str, dict[str, Any]] = {}
    comments: dict[str, list[str]] = {}
    canonical_by_col = {
        s.step["column"]: s.step["canonical"]
        for s in steps
        if s.active and s.step["op"] == "standardize_categoricals"
    }
    datetime_cols: list[Any] = []

    for c in raw_cols:
        p = prof[c]
        col = snake[c]
        spec: dict[str, Any] = {}
        complete = bool(len(kept)) and not _missing_series(kept[c]).any()
        if complete:
            spec["not_null"] = True
        if p.semantic == "identifier":
            spec["unique"] = True
            if p.inferred_type == "integer":
                spec["dtype"] = "integer"
            comments[col] = ["Identifier: must be unique after deduplication."]
        elif p.inferred_type == "email":
            spec["regex"] = EMAIL_REGEX
        elif p.inferred_type == "phone":
            spec["regex"] = E164_REGEX
            comments[col] = ["E.164 after standardize_phones (+<country code><number>)."]
        elif p.inferred_type == "boolean":
            spec["allowed"] = ["True", "False"]
        elif p.inferred_type == "datetime":
            spec["dtype"] = "datetime"
            datetime_cols.append(c)
        elif p.inferred_type in {"integer", "float"}:
            spec["dtype"] = p.inferred_type
            rng = _range_rule(_numbers(df[c]), integer=p.inferred_type == "integer")
            if rng:
                spec["range"] = rng
                comments[col] = [
                    f"Observed {_fmt(p.stats.get('min'))}..{_fmt(p.stats.get('max'))}; "
                    f"rule allows {rng['min']}..{rng['max']}."
                ]
        elif p.inferred_type == "categorical":
            allowed = canonical_by_col.get(col) or [cl["canonical"] for cl in p.clusters]
            if allowed and len(allowed) <= 20:
                spec["allowed"] = list(allowed)
        if spec:
            columns[col] = spec

    checks = []
    for i, a in enumerate(datetime_cols):
        for b in datetime_cols[i + 1:]:
            da, db = parse_dates(kept[a]), parse_dates(kept[b])
            both = da.notna() & db.notna()
            if int(both.sum()) < 3:
                continue
            if (da[both] <= db[both]).all() and not (da[both] == db[both]).all():
                checks.append({"name": f"{snake[a]}_not_after_{snake[b]}", "left": snake[a], "op": "<=", "right": snake[b]})
            elif (db[both] <= da[both]).all() and not (da[both] == db[both]).all():
                checks.append({"name": f"{snake[b]}_not_after_{snake[a]}", "left": snake[b], "op": "<=", "right": snake[a]})
    return {"columns": columns, "checks": checks}, comments


def _fmt(v: Any) -> str:
    if v is None:
        return "?"
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return f"{v:g}" if isinstance(v, float) else str(v)
